name: Main workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 10
      - id: ci
        name: npm ci
        run: npm ci
      - id: build
        name: Build
        run: npm run build
      - id: deploy
        name: Deploy
        run: bash ./.github/workflows/deploy.sh
        env:
          TOKEN: ${{ secrets.TOKEN }}
