name: Main Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: npm_run_build
        name: Build
        run: npm run build
      - id: deploy
        name: Deploy
        run: bash ./.github/workflows/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
