name: Main Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2.3.4
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: npm_run_build
        name: Build
        run: npm run build
      - id: deploy
        name: Deploy
        uses: Tarocch1/actions/github-push@main
        with:
          branch: gh-pages
          directory: dist
